# Generated by Django 3.1.1 on 2020-11-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(blank=True, null=True)),
                ('rg', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Binario', 'Não Binario')], max_length=100)),
                ('cor_pele', models.CharField(choices=[('Preta', 'Preta'), ('Parda', 'Parda'), ('Branca', 'Branca')], max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('idade_aparente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testemunha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=50)),
                ('rg', models.IntegerField(max_length=50)),
                ('nascimento', models.DateField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Binario', 'Não Binario')], max_length=100)),
                ('naturalidade', models.CharField(choices=[('Brasileiro', 'Brasileiro'), ('Estrangeiro', 'Estrangeiro')], max_length=100)),
                ('cor_pele', models.CharField(choices=[('Preta', 'Preta'), ('Parda', 'Parda'), ('Branca', 'Branca')], max_length=100)),
                ('fone', models.IntegerField(max_length=50)),
                ('residencia', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=50)),
                ('rg', models.IntegerField(max_length=50)),
                ('nascimento', models.DateField(max_length=50)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Não Binario', 'Não Binario')], max_length=100)),
                ('naturalidade', models.CharField(choices=[('Brasileiro', 'Brasileiro'), ('Estrangeiro', 'Estrangeiro')], max_length=100)),
                ('cor_pele', models.CharField(choices=[('Preta', 'Preta'), ('Parda', 'Parda'), ('Branca', 'Branca')], max_length=100)),
                ('fone', models.IntegerField(max_length=50)),
                ('residencia', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relato', models.CharField(max_length=400)),
                ('logradouro', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('local_especifico', models.CharField(max_length=100)),
                ('data', models.DateField(max_length=50)),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=100)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fato.autor')),
                ('testemunha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fato.testemunha')),
                ('vitima', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fato.vitima')),
            ],
        ),
    ]
